var da = new Date();
var currentTime = da.getTime();
var dob = prompt("Enter your dob");
var curentDate = new Date(dob);
var totalDate = da.getTime() - curentDate.getTime();
document.write('Time Spend in sec: ',Math.floor(totalDate / (1000)) , "<br/>");
document.write('Time Spend in Minutes: ',Math.floor(totalDate / (1000 * 60)) , "<br/>");
document.write('Time Spend in Hours: ',Math.floor(totalDate / (1000 * 60 * 60)) , "<br/>");
document.write('Time Spend in Days: ',Math.floor(totalDate / (1000 * 60 * 60 * 24)) , "<br/>");
document.write('Time Spend in Week: ',Math.floor(totalDate / (1000 * 60 * 60 * 24 * 7)) , "<br/>");
document.write('Time Spend in Months: ',Math.floor(totalDate / (1000 * 60 * 60 * 24 * 30.44)) , "<br/>");
document.write('Time Spend in Year: ',Math.floor(totalDate / (1000 * 60 * 60 * 24 * 365.25 )) , "<br/>");